### ISSUE TITLE
Malicious code detected by Sonar

### ISSUE THREAD

**Issue by ciepol** [ljharb/own-keys#2]
> The packages listed below contain Embedded Malicious Code. Upon installation, these packages execute scripts that gather system information and exfiltrate the data to the author's server.
>
> Weakness Sonatype CWE: [506](https://cwe.mitre.org/data/definitions/506.html)

Might have big impact as it's used for example by `eslint-plugin-imprt` via `es-abstract`.

As a temporary fix had to do `npm` override with `es-abstract` v 1.23.7:
```json
"overrides": {
  "es-abstract": "1.23.7"
}
```

**Comment by d1fferenz** [comment]
This package kills "yarn install" because Sonartype Nexus Repository prohibits it. In Nexus IQ this package gets a 10/10 Security Critical, Security Malicious and also a Integrity-Rating threat 😅

**Comment by webmutation** [comment]
same, if this part of a refactor it is being marked as malware injection by Sonatype Nexus

**Comment by ljharb** [comment]
This is a false positive in Nexus. Apparently the package used to exist in 2022, when it was malicious, but it was removed, with no trace left that it ever existed.

This package is completely safe and Nexus shouldn’t be warning on it.

**Comment by d1fferenz** [comment]
interesting to hear! :) To me, the 21 lines don't look suspicious at all. 😄
What's the proposed process from here? Should we inform Nexus to create a fix or reconsider their opinion?

**Comment by ljharb** [comment]
Please do so; if you can link to somewhere public I can comment on it as well.

**Comment by d1fferenz** [comment]
Okay thank you very much! I'll try to find a good solution tomorrow. It's getting dark in germany :)
I'll @ you if i found something suitable!

**Comment by d1fferenz** [comment]
Good Morning :)
I messaged the responsible colleague in my company to contact Sonar directly. I asked him to send them the link to this issue and reconsider the state of this package! They'll talk next Tuesday (07.01.2025 or 01/07/2025). I'll update this issue when i got news.
Happy new year!

(@ljharb)

**Comment by jurgensweere** [comment]
We had the same issue here with Nexus firewall. Sonatype has already updated their vulnerability database and own-keys is no longer marked malicious for version 1.0.0. and 1.0.1.

So this issue has been resolved for us

**Comment by d1fferenz** [comment]
Yeah, I can confirm that the problem seems to be resolved for us as well. I just tested it in different contexts. 👍🏻
